#!/usr/bin/env python3
"""
Generate 1,000 product ideas for Spark (800 physical + 200 SaaS).
No API key needed — uses template-based breakdowns with category-specific language.
Output: src/data/generated-physical.ts and src/data/generated-saas.ts
"""
import json
import hashlib
import random

random.seed(42)  # reproducible

# ============================================================
# PHYSICAL PRODUCT SEEDS — 800 ideas across 16 categories
# ============================================================

PHYSICAL_CATEGORIES = {
    "Home & Living": {
        "interests": ["home", "crafts"],
        "badges_pool": ["trending", "beginner", "lowCapital"],
        "items": [
            ("Soy Candles", 2, "$60-180", "Hand-pour in your kitchen, sell everywhere"),
            ("Reed Diffusers", 1, "$40-120", "Zero maintenance home fragrance"),
            ("Wax Melts", 1, "$30-100", "Cheapest entry into the scent game"),
            ("Room Sprays", 1, "$40-100", "Spray bottles + essential oils = profit"),
            ("Tufted Rugs", 3, "$300-600", "TikTok's favorite home craft"),
            ("Macrame Wall Hangings", 2, "$30-100", "Boho decor that sells on autopilot"),
            ("Custom Throw Pillows", 1, "$100-300", "Print-on-demand home decor"),
            ("Dried Flower Arrangements", 2, "$50-150", "Everlasting bouquets people love"),
            ("Terrazzo Coasters", 2, "$50-120", "Pour, polish, sell on Etsy"),
            ("Concrete Planters", 2, "$40-100", "Industrial chic from your garage"),
            ("Beeswax Wraps", 1, "$30-80", "Eco kitchen staple that sells itself"),
            ("Linen Napkins", 1, "$60-200", "Premium table setting, low effort"),
            ("Ceramic Mugs", 3, "$200-500", "Handmade mugs never go out of style"),
            ("Wooden Cutting Boards", 2, "$100-300", "Engrave them for premium pricing"),
            ("Hand-Poured Resin Trays", 2, "$60-150", "Jewelry trays with art appeal"),
            ("Woven Baskets", 2, "$50-150", "Storage meets style"),
            ("Scented Sachets", 1, "$20-60", "Tiny bags, big margins"),
            ("Floating Shelves", 2, "$80-250", "Simple woodwork, premium prices"),
            ("Decorative Candle Holders", 2, "$40-120", "Pair with candles for upsell"),
            ("Incense Holders", 2, "$30-100", "Ceramic + minimalist = sold"),
            ("Linen Curtains", 2, "$150-400", "High AOV, low competition"),
            ("Knitted Blankets", 3, "$100-300", "Chunky knit is always trending"),
            ("Wall Clocks", 2, "$60-200", "Minimalist designs sell on Etsy"),
            ("Terracotta Pots", 1, "$40-120", "Paint them, double the price"),
            ("Aromatherapy Pillows", 2, "$40-100", "Lavender-filled sleep helpers"),
            ("Mosaic Art Pieces", 3, "$80-250", "Unique wall art from broken tiles"),
            ("Fabric Coasters", 1, "$20-60", "Sew and sell sets of 4"),
            ("Ceramic Ring Dishes", 2, "$30-80", "Perfect gift under $20"),
            ("Rattan Mirror Frames", 2, "$60-200", "Boho bathroom essential"),
            ("Cotton Table Runners", 1, "$40-120", "Block print for premium look"),
            ("Acrylic Night Lights", 2, "$50-150", "LED + custom shapes = gift gold"),
            ("Potpourri Blends", 1, "$20-60", "Dried flowers + oils in pretty bags"),
            ("Woven Wall Art", 3, "$60-200", "Fiber art is gallery-worthy now"),
            ("Marble Bookends", 2, "$80-200", "Heavy, premium, desk decor"),
            ("Pressed Flower Frames", 2, "$40-120", "Nature art that sells fast"),
            ("Embroidered Hoop Art", 2, "$30-100", "Frame it, sell it, repeat"),
            ("Soapstone Sculptures", 3, "$100-300", "Handcarved decor from India"),
            ("Wooden Candle Holders", 2, "$40-120", "Lathe + finish = done"),
            ("Glass Terrariums", 2, "$60-200", "Mini ecosystems people collect"),
            ("Dried Herb Wreaths", 2, "$40-120", "Seasonal door decor"),
            ("Bamboo Utensil Sets", 1, "$30-100", "Eco kitchen, easy to source"),
            ("Jute Rugs", 2, "$100-300", "Natural fiber, high demand"),
            ("Ceramic Vases", 3, "$60-200", "Handmade pottery for flowers"),
            ("Resin Clocks", 2, "$60-180", "Ocean/galaxy themes sell best"),
            ("Leather Coasters", 2, "$40-120", "Stamp or engrave for custom"),
            ("Wooden Spice Racks", 2, "$60-200", "Kitchen organization niche"),
            ("Macrame Plant Hangers", 1, "$20-60", "Easiest macrame project"),
            ("Cement Candle Holders", 2, "$30-100", "Pour molds at home"),
            ("Linen Aprons", 1, "$40-120", "Kitchen + garden crossover"),
            ("Cork Placemats", 1, "$30-80", "Eco dining, easy sourcing"),
        ]
    },
    "Jewelry & Accessories": {
        "interests": ["jewelry", "fashion"],
        "badges_pool": ["trending", "beginner", "fastSale", "lowCapital"],
        "items": [
            ("Silver Jewelry", 2, "$100-400", "Timeless metal, endless designs"),
            ("Resin Jewelry", 2, "$50-150", "Trap flowers in resin, sell art"),
            ("Polymer Clay Earrings", 2, "$40-120", "TikTok's #1 craft business"),
            ("Beaded Bracelets", 1, "$30-80", "String beads, stack profits"),
            ("Wire Wrapped Crystals", 2, "$40-120", "Spiritual jewelry with high margins"),
            ("Hair Scrunchies", 1, "$30-80", "Sew fabric, sell in sets"),
            ("Enamel Pins", 2, "$150-400", "Design once, sell thousands"),
            ("Embroidered Patches", 2, "$80-200", "Custom patches for brands & fans"),
            ("Charm Bracelets", 1, "$40-120", "Mix and match sells more"),
            ("Pearl Necklaces", 2, "$80-250", "Freshwater pearls, huge markup"),
            ("Birthstone Rings", 2, "$60-200", "Personalized jewelry converts"),
            ("Anklets", 1, "$20-60", "Summer accessory, year-round sales"),
            ("Layered Necklace Sets", 2, "$60-200", "Bundle = higher AOV"),
            ("Minimalist Gold Rings", 2, "$80-250", "Dainty jewelry sells daily"),
            ("Macrame Earrings", 1, "$20-60", "Boho + handmade = Etsy gold"),
            ("Leather Bracelets", 2, "$40-120", "Stamped leather, unisex appeal"),
            ("Crystal Pendants", 2, "$40-120", "Healing crystals meet fashion"),
            ("Vintage Style Brooches", 2, "$40-120", "Nostalgic accessories trending"),
            ("Silk Hair Ties", 1, "$30-80", "Premium alternative to scrunchies"),
            ("Wooden Earrings", 2, "$30-100", "Laser cut for precision"),
            ("Initial Necklaces", 2, "$60-200", "Personalized = premium pricing"),
            ("Gemstone Studs", 2, "$60-200", "Simple stones, high margins"),
            ("Bangle Sets", 1, "$40-120", "Stack them, sell sets of 5"),
            ("Cuff Bracelets", 2, "$60-200", "Statement piece, higher price"),
            ("Tassel Earrings", 1, "$20-60", "Quick to make, easy to sell"),
            ("Coin Necklaces", 2, "$60-200", "Vintage coins on chains"),
            ("Seed Bead Rings", 1, "$20-60", "Tiny beads, TikTok trending"),
            ("Mood Rings", 1, "$30-80", "Nostalgia sells to millennials"),
            ("Signet Rings", 2, "$80-250", "Custom engraving adds value"),
            ("Hoop Earrings", 1, "$40-120", "Classic style, always selling"),
            ("Braided Leather Cords", 1, "$30-80", "Unisex necklaces and bracelets"),
            ("Pressed Flower Pendants", 2, "$40-120", "Real flowers in resin"),
            ("Turquoise Jewelry", 2, "$80-250", "Western style comeback"),
            ("Stacking Rings Set", 2, "$60-200", "Sell sets of 3-5 rings"),
            ("Name Plate Necklaces", 2, "$80-250", "Custom names in gold"),
            ("Ear Cuffs", 1, "$30-80", "No piercing needed, trending"),
            ("Chain Link Bracelets", 2, "$60-200", "Bold chain is back in style"),
            ("Locket Necklaces", 2, "$60-200", "Sentimental jewelry with photos"),
            ("Shell Jewelry", 1, "$20-60", "Beach vibes, summer sales peak"),
            ("Titanium Rings", 2, "$80-250", "Men's jewelry, growing market"),
            ("Glass Bead Earrings", 1, "$30-80", "Murano-style, handmade look"),
            ("Woven Friendship Bracelets", 1, "$20-60", "Nostalgia + custom colors"),
            ("Bar Necklaces", 2, "$60-200", "Engraved bars, minimalist"),
            ("Felt Flower Pins", 1, "$20-60", "Handmade brooches for coats"),
            ("Copper Jewelry", 2, "$40-120", "Affordable alternative to gold"),
            ("Threader Earrings", 1, "$30-80", "Delicate chain-through style"),
            ("Leather Keychain", 1, "$20-60", "Personalized keychains sell fast"),
            ("Boho Ring Sets", 1, "$40-120", "Multiple rings, one price"),
            ("Opal Pendants", 2, "$80-250", "Fire opal catches attention"),
            ("Ankle Bracelets Set", 1, "$30-80", "Beach season bestseller"),
        ]
    },
    "Beauty & Wellness": {
        "interests": ["beauty", "crafts"],
        "badges_pool": ["trending", "beginner", "lowCapital", "growing"],
        "items": [
            ("Handmade Soap Bars", 3, "$80-200", "Cold process soap, premium margins"),
            ("Bath Bombs", 2, "$40-120", "Color + fizz = Instagram gold"),
            ("Lip Balm", 2, "$50-150", "Tiny tubes, massive markup"),
            ("Aromatherapy Roll-Ons", 2, "$60-150", "Essential oil blends on the go"),
            ("Body Butter", 2, "$50-120", "Whip shea butter, sell luxury"),
            ("Hair Oil Blends", 1, "$40-100", "Ayurvedic oils trending globally"),
            ("Face Serums", 2, "$80-200", "Small bottles, huge perceived value"),
            ("Sugar Scrubs", 1, "$30-80", "Mix, jar, label, sell"),
            ("Beard Oil", 2, "$40-120", "Men's grooming is exploding"),
            ("Solid Shampoo Bars", 2, "$60-150", "Zero waste beauty movement"),
            ("Clay Face Masks", 2, "$40-120", "Mix clays + botanicals"),
            ("Herbal Tea Blends", 2, "$40-120", "Wellness + beauty crossover"),
            ("Whipped Soap", 2, "$40-120", "Fluffy texture, premium price"),
            ("Shower Steamers", 2, "$30-100", "Aromatherapy in the shower"),
            ("Cuticle Oil Pens", 1, "$30-80", "Nail care accessory, easy to make"),
            ("Body Mists", 1, "$40-100", "Lighter than perfume, sells more"),
            ("Bubble Bath", 1, "$30-80", "Classic self-care product"),
            ("Hand Cream", 2, "$40-120", "Small tubes, premium ingredients"),
            ("Salt Bath Soaks", 1, "$30-80", "Epsom salt + dried flowers"),
            ("Facial Toner", 2, "$50-150", "Rose water based, simple formula"),
            ("Coconut Oil Products", 1, "$30-80", "Multi-use, easy to brand"),
            ("Eye Cream", 2, "$60-200", "Small jar, high perceived value"),
            ("Dry Shampoo Powder", 1, "$30-80", "Natural alternative trending"),
            ("Charcoal Soap", 2, "$40-120", "Detox appeal sells to men too"),
            ("Aloe Vera Gel", 1, "$30-80", "Sunburn season bestseller"),
            ("Body Scrub Bars", 2, "$40-120", "Solid scrub, zero waste"),
            ("Hair Masks", 2, "$40-120", "Deep conditioning treatments"),
            ("Perfume Oil Rollerballs", 2, "$60-200", "Concentrated scent, travel size"),
            ("Goat Milk Soap", 2, "$50-150", "Niche soap with loyal buyers"),
            ("Vitamin C Serum", 2, "$80-200", "Brightening serum, huge demand"),
            ("Scalp Scrub", 2, "$40-120", "New category, growing fast"),
            ("Body Oil", 1, "$40-100", "Carrier oil + fragrance = done"),
            ("Teeth Whitening Kit", 2, "$80-250", "High demand, private label easy"),
            ("Jade Rollers", 1, "$20-60", "Import and brand, simple"),
            ("Gua Sha Stones", 1, "$20-60", "Facial massage tool trending"),
            ("Nail Polish", 3, "$200-500", "Non-toxic formulas sell premium"),
            ("Brow Lamination Kit", 2, "$60-150", "At-home beauty treatment"),
            ("Lash Serum", 2, "$80-200", "Growth serums have loyal buyers"),
            ("Makeup Remover Pads", 1, "$20-60", "Reusable pads, eco angle"),
            ("Turmeric Skincare", 2, "$40-120", "Ayurvedic glow products"),
            ("Rice Water Spray", 1, "$20-60", "K-beauty inspired, simple to make"),
            ("Silk Pillowcases", 1, "$60-200", "Beauty sleep marketing angle"),
            ("Foot Soak Blends", 1, "$30-80", "Relaxation category, easy entry"),
            ("Hand Soap Bars", 2, "$40-120", "Kitchen + bathroom staple"),
            ("Deodorant Cream", 2, "$40-120", "Natural deo, growing market"),
            ("Lip Scrub", 1, "$20-60", "Sugar + oil + flavor"),
            ("Hair Accessories Set", 1, "$30-80", "Clips, pins, ties bundle"),
            ("Collagen Powder", 2, "$100-300", "Wellness supplement, white label"),
            ("CBD Balm", 3, "$150-400", "Pain relief topical, regulated"),
            ("Facial Mist Spray", 1, "$30-80", "Rose water + glycerin"),
        ]
    },
    "Pets": {
        "interests": ["pets"],
        "badges_pool": ["trending", "growing", "beginner"],
        "items": [
            ("Pet ID Tags", 2, "$100-300", "Engraved tags for fur babies"),
            ("Pet Bandanas", 2, "$40-100", "Fabric + sewing machine = done"),
            ("Dog Treats", 2, "$60-150", "Bake healthy treats at home"),
            ("Cat Toys", 1, "$30-80", "Catnip mice sell themselves"),
            ("Pet Bow Ties", 1, "$30-60", "Wedding pet accessories trending"),
            ("Dog Leashes", 2, "$60-200", "Paracord or leather, handmade"),
            ("Pet Beds", 2, "$100-300", "Fleece + stuffing, sell premium"),
            ("Dog Collar Charms", 1, "$20-60", "Tiny add-on, big margins"),
            ("Cat Scratching Posts", 2, "$80-250", "Sisal rope + wood base"),
            ("Pet Portrait Commissions", 3, "$50-200", "Digital art of people's pets"),
            ("Dog Poop Bag Holders", 1, "$30-80", "Sew fabric holders, practical gift"),
            ("Pet Clothing", 2, "$60-200", "Dog sweaters and raincoats"),
            ("Freeze-Dried Treats", 2, "$80-200", "Premium pet snacks"),
            ("Pet Shampoo", 2, "$40-120", "Natural ingredients, gentle formula"),
            ("Dog Harness", 2, "$80-250", "No-pull harness, high demand"),
            ("Cat Window Perch", 2, "$60-150", "Suction cup shelf for cats"),
            ("Pet First Aid Kit", 1, "$40-100", "Bundle common items together"),
            ("Dog Training Treats", 2, "$40-120", "Small, soft, healthy"),
            ("Pet Memorial Items", 2, "$40-120", "Paw print ornaments, keepsakes"),
            ("Rabbit Toys", 1, "$20-60", "Chew toys from natural materials"),
            ("Dog Cooling Mat", 1, "$40-120", "Summer essential for pets"),
            ("Cat Puzzle Feeder", 2, "$40-120", "Enrichment toys growing fast"),
            ("Pet Carrier Bags", 2, "$80-250", "Stylish pet transport"),
            ("Dog Snuffle Mat", 2, "$40-120", "Enrichment toy, easy to make"),
            ("Pet Odor Spray", 1, "$30-80", "Essential oil based, safe formula"),
            ("Personalized Food Bowls", 2, "$40-120", "Ceramic with pet's name"),
            ("Bird Toys", 1, "$20-60", "Wooden and rope toys for parrots"),
            ("Fish Tank Decorations", 1, "$30-80", "Resin figures for aquariums"),
            ("Dog Waste Station", 2, "$60-200", "Outdoor dispenser with bags"),
            ("Cat Collar Bells", 1, "$20-60", "Safety bells, cute designs"),
            ("Pet Dental Chews", 2, "$40-120", "Dental health treats"),
            ("Hamster Habitat Accessories", 1, "$20-60", "Wheels, tunnels, hideouts"),
            ("Dog Birthday Kit", 1, "$30-80", "Hat + treat + bandana bundle"),
            ("Pet Travel Water Bottle", 1, "$30-80", "Portable bowl + bottle combo"),
            ("Cat Litter Mat", 1, "$30-80", "Traps litter, easy to clean"),
            ("Dog Raincoat", 2, "$40-120", "Waterproof, reflective options"),
            ("Pet Stroller", 2, "$100-300", "Senior pet mobility solution"),
            ("Cat Tunnel", 1, "$30-80", "Collapsible play tunnel"),
            ("Pet Camera Treats Dispenser", 3, "$150-400", "Smart pet tech, white label"),
            ("Dog Anxiety Vest", 2, "$60-200", "Thunder shirt alternative"),
        ]
    },
    "Food & Beverage": {
        "interests": ["food"],
        "badges_pool": ["trending", "provenIncome", "growing"],
        "items": [
            ("Hot Sauce", 3, "$200-500", "Small batch heat with a story"),
            ("Spice Blends", 2, "$80-200", "Mix, label, sell on Amazon"),
            ("Granola & Trail Mix", 2, "$60-150", "Healthy snacking is massive"),
            ("Flavored Honey", 2, "$80-200", "Infused honey in pretty jars"),
            ("Cookie Mixes in Jars", 1, "$40-100", "Layer ingredients, sell the jar"),
            ("Beef Jerky", 3, "$200-500", "Dehydrate and season at home"),
            ("Nut Butter", 2, "$80-200", "Blend nuts, add flavors, jar it"),
            ("Cold Brew Coffee", 2, "$100-300", "Concentrate in bottles"),
            ("Kombucha", 3, "$150-400", "Fermented tea, loyal customers"),
            ("Specialty Popcorn", 2, "$60-150", "Flavored popcorn in tins"),
            ("Dried Fruit Snacks", 2, "$80-200", "Dehydrate seasonal fruit"),
            ("Infused Olive Oil", 2, "$80-200", "Garlic, chili, herb infusions"),
            ("Artisan Chocolate", 3, "$200-500", "Bean-to-bar craft chocolate"),
            ("Jam & Preserves", 2, "$60-150", "Seasonal fruit, year-round sales"),
            ("Matcha Powder", 2, "$100-300", "Import and brand, huge demand"),
            ("Flavored Salt", 1, "$30-80", "Truffle salt, smoked salt, etc."),
            ("Energy Balls", 2, "$40-120", "No-bake protein snacks"),
            ("Protein Bars", 2, "$100-300", "Private label or homemade"),
            ("Pickled Vegetables", 2, "$60-150", "Fermented foods trending"),
            ("BBQ Sauce", 2, "$100-300", "Regional flavors sell online"),
            ("Pasta Sauce", 2, "$100-300", "Homemade taste, jarred convenience"),
            ("Tea Blends", 2, "$60-150", "Loose leaf tea, premium packaging"),
            ("Flavored Butter", 2, "$60-150", "Compound butters in rolls"),
            ("Dried Mushroom Blends", 2, "$80-200", "Umami powders, chef market"),
            ("Caramel Sauce", 2, "$60-150", "Salted caramel everything"),
            ("Infused Vinegar", 2, "$60-150", "Fruit vinegar for cooking"),
            ("Candied Nuts", 1, "$40-100", "Sweet + salty snack combo"),
            ("Bone Broth", 2, "$100-300", "Health food, premium pricing"),
            ("Smoothie Powder Mix", 2, "$80-200", "Pre-mixed smoothie blends"),
            ("Chili Crisp Oil", 2, "$80-200", "Crunchy chili oil is trending"),
            ("Cocktail Mixers", 2, "$80-200", "Craft mixers for home bars"),
            ("Salad Dressing", 2, "$60-150", "Unique flavors, clean label"),
            ("Cake Pop Kits", 1, "$40-100", "DIY baking kits for gifts"),
            ("Flavored Lemonade Mix", 1, "$30-80", "Lavender, strawberry, etc."),
            ("Organic Baby Food", 3, "$200-500", "Premium baby food pouches"),
            ("Mushroom Coffee", 2, "$100-300", "Functional coffee trending"),
            ("Dried Herbs", 1, "$30-80", "Garden to package, simple"),
            ("Curry Paste", 2, "$60-150", "Authentic recipes in jars"),
            ("Flavored Syrup", 2, "$60-150", "Coffee syrups for home baristas"),
            ("Seaweed Snacks", 2, "$80-200", "Asian snack going mainstream"),
        ]
    },
    "Kids & Baby": {
        "interests": ["kids"],
        "badges_pool": ["trending", "beginner", "growing", "lowCapital"],
        "items": [
            ("Baby Clothes (Organic)", 2, "$200-500", "Organic cotton onesies sell fast"),
            ("Wooden Toys", 3, "$100-300", "Montessori parents love these"),
            ("Sensory Play Kits", 1, "$40-100", "Bundle textures, colors, shapes"),
            ("Kids Art Kits", 1, "$40-120", "Pre-packed creative supplies"),
            ("Baby Bibs", 1, "$30-80", "Silicone or fabric, easy to brand"),
            ("Teething Toys", 2, "$40-120", "Silicone food-grade teethers"),
            ("Baby Milestone Cards", 1, "$20-60", "Monthly photo prop cards"),
            ("Kids Lunch Boxes", 2, "$60-200", "Bento style for school"),
            ("Baby Swaddles", 1, "$40-120", "Muslin wraps, gender neutral"),
            ("Quiet Books", 3, "$60-200", "Felt activity books for toddlers"),
            ("Kids Aprons", 1, "$30-80", "Mini chef sets for cooking"),
            ("Baby Mobiles", 2, "$40-120", "Nursery decor + toy combo"),
            ("Play Dough Kits", 1, "$30-80", "Homemade dough + tools"),
            ("Kids Growth Charts", 1, "$30-80", "Wall rulers, wood or canvas"),
            ("Pacifier Clips", 1, "$20-60", "Silicone bead chains"),
            ("Baby Bath Toys", 1, "$30-80", "Stacking cups, squirt toys"),
            ("Kids Personalized Books", 3, "$100-300", "Custom story with child's name"),
            ("Nursery Art Prints", 1, "$20-60", "Animal prints, neutral tones"),
            ("Baby Headbands", 1, "$20-60", "Soft nylon, bow designs"),
            ("Kids Dress-Up Costumes", 2, "$60-200", "Princess, superhero, animal"),
            ("Baby Booties", 2, "$30-80", "Knitted or leather, tiny sizes"),
            ("Kids Backpacks", 2, "$60-200", "Animal shaped, toddler size"),
            ("Educational Flashcards", 1, "$20-60", "ABCs, animals, shapes"),
            ("Baby Changing Pad Covers", 1, "$30-80", "Fitted muslin covers"),
            ("Kids Puzzle Sets", 2, "$40-120", "Wooden puzzles for ages 2-6"),
            ("Baby Name Signs", 2, "$40-120", "Nursery wall decor, laser cut"),
            ("Kids Rain Boots", 2, "$60-200", "Printed rubber boots"),
            ("Baby Burp Cloths", 1, "$20-60", "Muslin, multi-pack sells"),
            ("Kids Water Bottles", 1, "$30-80", "Spill-proof, fun designs"),
            ("Toddler Utensil Sets", 1, "$20-60", "Silicone forks and spoons"),
            ("Baby Sound Machines", 2, "$60-200", "White noise, portable"),
            ("Kids Night Lights", 2, "$40-120", "LED animal shapes"),
            ("Baby Memory Books", 2, "$40-120", "First year journal"),
            ("Kids Sticker Books", 1, "$20-60", "Reusable stickers, themes"),
            ("Baby Carrier Cover", 1, "$30-80", "Weather shield for carriers"),
            ("Kids Tent/Teepee", 2, "$80-250", "Indoor play tent"),
            ("Baby Diaper Caddy", 1, "$30-80", "Felt organizer basket"),
            ("Kids Science Kits", 2, "$60-200", "STEM experiments at home"),
            ("Baby Blankets", 2, "$40-120", "Minky fabric, custom names"),
            ("Kids Gardening Set", 1, "$30-80", "Mini tools + seeds kit"),
        ]
    },
    "Stationery & Art": {
        "interests": ["design", "crafts"],
        "badges_pool": ["beginner", "lowCapital", "fastSale"],
        "items": [
            ("Sticker Packs", 1, "$30-100", "Design once, print and sell forever"),
            ("Greeting Cards", 1, "$40-120", "Occasions drive repeat purchases"),
            ("Washi Tape", 2, "$200-500", "Custom designs, loyal collectors"),
            ("Art Prints", 1, "$20-80", "Digital art, physical sales"),
            ("Custom Stamps", 2, "$100-300", "Rubber stamps for crafters"),
            ("Bookmarks", 1, "$20-60", "Resin, metal, or paper designs"),
            ("Planner Inserts", 1, "$20-60", "Printable or physical pages"),
            ("Calligraphy Kits", 2, "$40-120", "Beginner sets with guides"),
            ("Watercolor Palettes", 2, "$60-200", "Curated color sets"),
            ("Sketchbooks", 2, "$60-200", "Hardcover, quality paper"),
            ("Vinyl Stickers", 1, "$20-60", "Waterproof, laptop-sized"),
            ("Wax Seal Kits", 2, "$40-120", "Vintage letter sealing trend"),
            ("Bullet Journal Supplies", 1, "$30-100", "Stencils, tapes, pens bundle"),
            ("Postcards", 1, "$20-60", "Travel and art themes"),
            ("Desk Organizers", 2, "$40-120", "Wooden or acrylic pen holders"),
            ("Hand-Lettered Signs", 2, "$40-120", "Custom quotes on wood"),
            ("Pencil Cases", 1, "$30-80", "Fabric rolls or leather"),
            ("Paper Flower Kits", 2, "$40-120", "DIY crepe paper flowers"),
            ("Origami Paper Sets", 1, "$20-60", "Patterned paper packs"),
            ("Erasable Markers", 1, "$30-80", "Whiteboard markers, colors"),
            ("Coloring Books (Adult)", 2, "$60-200", "Niche themes sell well"),
            ("Fountain Pen Ink", 2, "$60-200", "Boutique colors for pen lovers"),
            ("Notebook Sets", 1, "$40-120", "Themed journal bundles"),
            ("Paint-By-Number Kits", 2, "$60-200", "Custom photo kits trending"),
            ("Embossing Powder", 1, "$30-80", "Card-making essential"),
            ("Brush Pen Sets", 2, "$40-120", "Calligraphy + art dual use"),
            ("Paper Tape Rolls", 1, "$20-60", "Decorative craft tape"),
            ("Desk Mats", 2, "$40-120", "Large mouse pads with art"),
            ("Zipper Pouches", 1, "$20-60", "Fabric pencil cases, cute prints"),
            ("Scrapbook Kits", 2, "$40-120", "Paper, stickers, embellishments"),
            ("Clipboard Folios", 2, "$40-120", "Professional meeting essential"),
            ("Stamp Pad Ink Sets", 1, "$20-60", "Multi-color ink pads"),
            ("Letter Writing Kits", 1, "$30-80", "Pen pal revival trend"),
            ("Craft Paper Packs", 1, "$20-60", "Patterned sheets for projects"),
            ("Drawing Pencil Sets", 1, "$30-80", "Graphite range for artists"),
            ("Gift Wrap Rolls", 1, "$30-80", "Unique designs, eco paper"),
            ("Tape Dispensers", 1, "$20-60", "Cute designs for desk"),
            ("Index Card Holders", 1, "$20-60", "Study tool, simple product"),
            ("Cork Boards", 2, "$40-120", "Pin boards with frames"),
            ("Acrylic Desk Signs", 2, "$40-120", "Custom name plates"),
        ]
    },
    "Clothing & Apparel": {
        "interests": ["fashion", "design"],
        "badges_pool": ["trending", "fastSale", "provenIncome"],
        "items": [
            ("Screen Printed T-Shirts", 2, "$200-500", "Design + print + sell on Etsy"),
            ("Tie-Dye Clothing", 2, "$80-200", "Festival season goldmine"),
            ("Crochet Bags", 3, "$40-120", "Handmade totes and clutches"),
            ("Custom Embroidered Hats", 2, "$100-300", "Snapbacks with custom logos"),
            ("Handmade Tote Bags", 1, "$40-120", "Canvas + screen print"),
            ("Block Print Clothing", 2, "$80-200", "Indian craft, global market"),
            ("Linen Dresses", 2, "$100-300", "Natural fabric, premium pricing"),
            ("Graphic Socks", 1, "$40-120", "Fun designs, impulse buy"),
            ("Beanies & Knit Hats", 2, "$40-120", "Winter essential, year-round online"),
            ("Handmade Scarves", 2, "$40-120", "Silk, wool, or cotton"),
            ("Printed Bandanas", 1, "$30-80", "Fashion + utility combo"),
            ("Kimono Robes", 2, "$60-200", "Loungewear meets fashion"),
            ("Bucket Hats", 1, "$40-120", "Gen Z favorite, easy to brand"),
            ("Gym Shorts", 2, "$100-300", "Athletic wear, POD possible"),
            ("Linen Shirts", 2, "$80-200", "Resort wear trending"),
            ("Yoga Leggings", 2, "$100-300", "Print-on-demand athleisure"),
            ("Handknit Sweaters", 3, "$100-300", "Chunky knits command premium"),
            ("Denim Jackets (Painted)", 3, "$80-200", "Custom art on denim"),
            ("Swimwear", 2, "$150-400", "Seasonal but high margins"),
            ("Crop Tops", 1, "$40-120", "Streetwear staple"),
            ("Silk Sleep Masks", 1, "$30-80", "Gift set add-on item"),
            ("Convertible Dresses", 2, "$100-300", "One dress, multiple styles"),
            ("Patchwork Quilted Jackets", 3, "$100-300", "Upcycled fashion trend"),
            ("Crochet Tops", 3, "$40-120", "Summer festival wear"),
            ("Custom Sneaker Painting", 3, "$100-300", "Air Force 1 customs"),
            ("Fleece Vests", 2, "$60-200", "Outdoor casual trending"),
            ("Sarong Wraps", 1, "$30-80", "Beach + resort essential"),
            ("Embroidered Jeans", 3, "$80-200", "Custom denim art"),
            ("Athleisure Sets", 2, "$100-300", "Matching sets sell more"),
            ("Cotton Kurtas", 1, "$40-120", "Indian ethnic wear, global shipping"),
            ("Printed Pajama Sets", 2, "$60-200", "Matching PJ sets trending"),
            ("Upcycled Denim Bags", 2, "$40-120", "Sustainable fashion angle"),
            ("Custom Jerseys", 2, "$80-200", "Sports fan market"),
            ("Leather Belts", 2, "$60-200", "Handcrafted, stamped designs"),
            ("Wool Mittens", 2, "$30-80", "Hand-felted winter accessories"),
            ("Hawaiian Shirts", 2, "$60-200", "Vintage resurgence"),
            ("Knitted Baby Booties", 2, "$20-60", "Gift market, always selling"),
            ("Canvas Aprons", 1, "$40-120", "Barista + craft market"),
            ("Printed Hijabs", 2, "$60-200", "Modest fashion, huge market"),
            ("Corduroy Bags", 2, "$40-120", "Retro texture comeback"),
        ]
    },
    "Tech & Gadgets": {
        "interests": ["tech"],
        "badges_pool": ["trending", "fastSale", "growing"],
        "items": [
            ("Custom Phone Cases", 1, "$40-120", "Design + print on demand"),
            ("LED Strip Kits", 1, "$40-120", "Room lighting, gaming setups"),
            ("Wireless Chargers (Custom)", 2, "$60-200", "Branded charging pads"),
            ("Cable Organizers", 1, "$30-80", "Leather or silicone wraps"),
            ("Laptop Stands", 2, "$60-200", "Wooden or aluminum designs"),
            ("Keyboard Wrist Rests", 2, "$40-120", "Resin or wood, artisan market"),
            ("Desk Cable Management", 1, "$30-80", "Under-desk clips and trays"),
            ("Custom Keycaps", 3, "$100-300", "Artisan keycaps for mech keyboards"),
            ("Webcam Covers", 1, "$20-60", "Privacy accessory, bulk import"),
            ("Phone Grip Stands", 1, "$30-80", "PopSocket alternatives, custom"),
            ("Portable Speakers (Branded)", 2, "$80-250", "White label bluetooth speakers"),
            ("USB Hubs (Custom)", 2, "$60-200", "Multi-port with logo"),
            ("Tablet Stylus Pen", 1, "$30-80", "Universal stylus, import and brand"),
            ("Smart Home Sensors", 3, "$100-300", "DIY smart home kits"),
            ("Desk Humidifier", 1, "$30-80", "Mini USB humidifiers"),
            ("Bluetooth Earbuds Case", 1, "$20-60", "Silicone cases for AirPods"),
            ("Monitor Light Bar", 2, "$60-200", "Screen-top LED bars"),
            ("Desk Fan (USB)", 1, "$20-60", "Small fans, branded"),
            ("Phone Tripod Mount", 1, "$20-60", "Content creator essential"),
            ("Portable Power Bank", 2, "$60-200", "Custom branded batteries"),
            ("Gaming Mouse Pad", 2, "$40-120", "XXL pads with custom art"),
            ("Smart Plug (White Label)", 2, "$60-200", "WiFi plugs, app controlled"),
            ("Desk Lamp (LED)", 2, "$40-120", "Touch-dimming work lamps"),
            ("Mechanical Keyboard Kit", 3, "$150-400", "DIY keyboard enthusiast market"),
            ("Cord Winder Spools", 1, "$20-60", "Earbud and cable organizers"),
            ("Screen Cleaning Kit", 1, "$20-60", "Spray + cloth + case"),
            ("Ring Light (Small)", 1, "$30-80", "Clip-on for phones"),
            ("Laptop Sleeve", 1, "$30-80", "Felt or leather, custom sizes"),
            ("Desk Mat (Leather)", 2, "$60-200", "Premium workspace accessory"),
            ("Smart Thermometer", 2, "$60-200", "Kitchen or health, bluetooth"),
        ]
    },
    "Eco & Sustainability": {
        "interests": ["home", "crafts"],
        "badges_pool": ["trending", "growing", "beginner", "lowCapital"],
        "items": [
            ("Reusable Produce Bags", 1, "$30-80", "Mesh bags for grocery shopping"),
            ("Bamboo Toothbrushes", 1, "$40-120", "Eco bathroom staple"),
            ("Compostable Phone Cases", 2, "$60-200", "Biodegradable tech accessories"),
            ("Beeswax Food Wraps", 1, "$30-80", "Replace plastic wrap, easy to make"),
            ("Reusable Straws (Metal)", 1, "$30-80", "Straw + cleaner + pouch set"),
            ("Zero Waste Starter Kit", 1, "$60-200", "Bundle eco essentials"),
            ("Biodegradable Glitter", 1, "$30-80", "Festival + craft market"),
            ("Seed Paper Cards", 2, "$40-120", "Plantable greeting cards"),
            ("Solar Garden Lights", 2, "$60-200", "Import and brand, seasonal"),
            ("Reusable Coffee Cups", 1, "$30-80", "Bamboo fiber travel mugs"),
            ("Cloth Napkins Set", 1, "$30-80", "Replace paper, premium dining"),
            ("Eco Laundry Sheets", 2, "$60-200", "Detergent strips, no plastic"),
            ("Compost Bin (Kitchen)", 2, "$60-200", "Countertop composting"),
            ("Reusable Sandwich Bags", 1, "$30-80", "Silicone food storage"),
            ("Bamboo Cutlery Set", 1, "$20-60", "Travel utensil roll"),
            ("Natural Loofah Sponges", 1, "$20-60", "Biodegradable kitchen sponge"),
            ("Seed Bomb Kits", 1, "$20-60", "Wildflower seed balls"),
            ("Reusable Paper Towels", 1, "$30-80", "Swedish dishcloths trending"),
            ("Eco Gift Wrap", 1, "$20-60", "Fabric wrapping cloths"),
            ("Plant-Based Candles", 2, "$40-120", "Coconut wax + wooden wick"),
            ("Recycled Notebook", 1, "$30-80", "Upcycled paper journals"),
            ("Natural Cleaning Products", 2, "$60-200", "Vinegar + essential oil kits"),
            ("Reusable Ice Packs", 1, "$20-60", "Gel packs for lunch boxes"),
            ("Bamboo Hair Brush", 1, "$20-60", "Natural bristle, eco handle"),
            ("Eco Yoga Mat", 2, "$80-250", "Cork or natural rubber"),
            ("Upcycled Candle Holders", 2, "$30-80", "Wine bottle + cement base"),
            ("Natural Bug Spray", 2, "$40-120", "Essential oil based repellent"),
            ("Silicone Food Covers", 1, "$20-60", "Stretch lids for bowls"),
            ("Eco Tote Bags", 1, "$30-80", "Organic cotton, printed"),
            ("Worm Composting Kit", 2, "$60-200", "Indoor vermicompost system"),
        ]
    },
    "Fitness & Sports": {
        "interests": ["fitness"],
        "badges_pool": ["trending", "growing", "provenIncome"],
        "items": [
            ("Resistance Bands Set", 1, "$40-120", "Import, brand, bundle"),
            ("Yoga Blocks", 1, "$30-80", "Cork or foam, branded"),
            ("Jump Ropes", 1, "$30-80", "Weighted handles, speed ropes"),
            ("Gym Bags", 2, "$60-200", "Duffel bags with shoe compartment"),
            ("Water Bottles (Insulated)", 2, "$60-200", "Branded hydration bottles"),
            ("Foam Rollers", 1, "$40-120", "Recovery tool, always selling"),
            ("Wrist Wraps", 1, "$30-80", "Lifting accessories, bulk import"),
            ("Gym Towels", 1, "$30-80", "Microfiber, branded"),
            ("Massage Gun Attachments", 2, "$40-120", "Universal heads, 3D printed"),
            ("Lifting Straps", 1, "$20-60", "Nylon or leather straps"),
            ("Yoga Mat Bags", 1, "$30-80", "Canvas carriers with strap"),
            ("Sweatbands", 1, "$20-60", "Headbands and wristbands"),
            ("Workout Gloves", 1, "$30-80", "Lifting gloves, import and brand"),
            ("Agility Ladder", 1, "$30-80", "Speed training tool"),
            ("Meditation Cushion", 2, "$40-120", "Buckwheat fill, linen cover"),
            ("Protein Shaker Bottle", 1, "$20-60", "Custom branded shakers"),
            ("Fitness Tracker Bands", 1, "$20-60", "Replacement bands, custom colors"),
            ("Ab Roller", 1, "$20-60", "Core workout tool, import"),
            ("Grip Strengtheners", 1, "$20-60", "Adjustable hand grippers"),
            ("Skipping Rope Mat", 2, "$40-120", "Impact-absorbing jump mat"),
            ("Ankle Weights", 1, "$30-80", "Adjustable weight, import"),
            ("Gym Chalk Bags", 1, "$20-60", "Climbing + lifting accessory"),
            ("Balance Board", 2, "$60-200", "Wooden balance trainer"),
            ("Stretching Strap", 1, "$20-60", "Yoga stretch band with loops"),
            ("Mini Stepper", 2, "$60-200", "Under-desk fitness device"),
            ("Cooling Towel", 1, "$20-60", "Instant cool technology"),
            ("Tennis Grip Tape", 1, "$20-60", "Replacement grips, bulk"),
            ("Swim Cap", 1, "$20-60", "Silicone caps, custom prints"),
            ("Paddle Ball Set", 1, "$30-80", "Beach + park game set"),
            ("Workout Timer", 2, "$40-120", "LED interval timer, tabata"),
        ]
    },
    "Garden & Outdoor": {
        "interests": ["home", "crafts"],
        "badges_pool": ["trending", "growing", "beginner"],
        "items": [
            ("Herb Garden Kits", 1, "$30-80", "Seeds + soil + pots bundle"),
            ("Garden Tool Sets", 2, "$60-200", "Trowel + pruner + gloves"),
            ("Plant Markers", 1, "$20-60", "Ceramic or wood garden labels"),
            ("Bird Feeders", 2, "$40-120", "Wooden or ceramic designs"),
            ("Hanging Planters", 1, "$30-80", "Macrame or ceramic"),
            ("Seed Starting Kits", 1, "$20-60", "Trays + soil + seed variety"),
            ("Garden Gnomes", 2, "$40-120", "Resin figurines, custom paint"),
            ("Outdoor Candles", 2, "$40-120", "Citronella + decorative"),
            ("Fairy Garden Supplies", 1, "$30-80", "Miniature accessories"),
            ("Raised Bed Kits", 3, "$100-300", "Cedar planter box kits"),
            ("Watering Cans", 1, "$30-80", "Decorative metal or copper"),
            ("Garden Stepping Stones", 2, "$40-120", "Mosaic or stamped concrete"),
            ("Succulent Pots", 1, "$20-60", "Tiny cement or ceramic pots"),
            ("Wind Chimes", 2, "$40-120", "Metal, bamboo, or glass"),
            ("Garden Knee Pad", 1, "$20-60", "Memory foam, washable cover"),
            ("Outdoor Thermometer", 1, "$20-60", "Decorative wall thermometer"),
            ("Solar Stake Lights", 1, "$30-80", "Path lights, color changing"),
            ("Hose Nozzle", 1, "$20-60", "Multi-pattern brass nozzle"),
            ("Compost Tumbler", 3, "$100-300", "Outdoor rotating composter"),
            ("Bonsai Starter Kit", 2, "$40-120", "Tree + pot + tools + guide"),
            ("Garden Kneeling Bench", 2, "$40-120", "Fold-up bench/kneeler"),
            ("Herb Drying Rack", 2, "$30-80", "Mesh hanging rack"),
            ("Plant Support Stakes", 1, "$20-60", "Bamboo or metal stakes"),
            ("Outdoor Cushions", 2, "$60-200", "Weather-resistant fabric"),
            ("Garden Apron", 1, "$30-80", "Multi-pocket work apron"),
            ("Propagation Station", 2, "$30-80", "Glass tubes + wood holder"),
            ("Mushroom Grow Kit", 2, "$40-120", "Oyster or shiitake at home"),
            ("Vertical Garden Frame", 3, "$80-250", "Wall-mounted planter system"),
            ("Butterfly House", 2, "$30-80", "Wooden garden habitat"),
            ("Rain Gauge", 1, "$20-60", "Decorative measuring device"),
        ]
    },
    "Art & Craft Supplies": {
        "interests": ["crafts", "design"],
        "badges_pool": ["beginner", "lowCapital", "lessCrowded"],
        "items": [
            ("Resin Art Kits", 2, "$60-200", "Epoxy + molds + pigment bundle"),
            ("Candle Making Kits", 2, "$40-120", "Wax + wicks + fragrance set"),
            ("Soap Making Kits", 2, "$40-120", "Melt-and-pour starter sets"),
            ("Embroidery Kits", 1, "$30-80", "Hoop + pattern + thread"),
            ("Tie-Dye Kits", 1, "$30-80", "Dyes + rubber bands + gloves"),
            ("Pottery Tool Sets", 2, "$40-120", "Clay tools for beginners"),
            ("Macrame Cord Bundles", 1, "$20-60", "Cotton rope in colors"),
            ("Punch Needle Kits", 2, "$40-120", "Rug hooking made easy"),
            ("Weaving Loom Kits", 2, "$40-120", "Small frame looms + yarn"),
            ("Screen Printing Kit", 2, "$80-250", "Starter set for t-shirt printing"),
            ("Alcohol Ink Sets", 2, "$40-120", "Vibrant inks for art"),
            ("Leather Craft Kits", 2, "$60-200", "Leather + tools + patterns"),
            ("Sewing Kits", 1, "$20-60", "Portable repair and craft kits"),
            ("Jewelry Making Kits", 1, "$30-80", "Beads + wire + pliers"),
            ("Woodburning Kits", 2, "$40-120", "Pyrography pen + tips"),
            ("Needle Felting Kits", 2, "$30-80", "Wool + needles + foam"),
            ("Mosaic Tile Kits", 2, "$40-120", "Glass tiles + adhesive + grout"),
            ("Crochet Starter Kits", 1, "$20-60", "Hook + yarn + pattern"),
            ("Block Printing Kits", 2, "$40-120", "Stamps + ink + fabric"),
            ("Basket Weaving Kits", 2, "$30-80", "Reed + base + pattern"),
            ("Terrarium Kits", 2, "$40-120", "Glass + soil + plants + tools"),
            ("Paper Quilling Kits", 1, "$20-60", "Paper strips + slotted tool"),
            ("Glass Painting Kits", 1, "$30-80", "Paints + brushes + glass items"),
            ("Air Dry Clay Kits", 1, "$20-60", "Clay + tools + paint"),
            ("Batik Making Kits", 2, "$40-120", "Wax + dyes + fabric"),
            ("Fabric Dyeing Kits", 2, "$40-120", "Natural dyes from plants"),
            ("Wire Art Kits", 1, "$20-60", "Wire + pliers + templates"),
            ("Silicone Mold Making Kit", 2, "$40-120", "Make custom resin molds"),
            ("Cross Stitch Kits", 1, "$20-60", "Pattern + fabric + thread"),
            ("Book Binding Kit", 2, "$40-120", "Make journals from scratch"),
        ]
    },
    "Personalized & Custom": {
        "interests": ["design", "crafts"],
        "badges_pool": ["trending", "provenIncome", "fastSale"],
        "items": [
            ("Custom Engraved Jewelry", 2, "$80-250", "Names, dates, coordinates"),
            ("Personalized Mugs", 1, "$40-120", "Photos + text on mugs"),
            ("Custom Pet Portraits", 3, "$50-200", "Digital art commissions"),
            ("Engraved Cutting Boards", 2, "$60-200", "Wedding gift bestseller"),
            ("Custom Map Art", 2, "$40-120", "City maps, star maps"),
            ("Personalized Baby Blankets", 2, "$40-120", "Embroidered name + date"),
            ("Custom Family Portraits", 3, "$80-250", "Illustrated family drawings"),
            ("Engraved Pens", 1, "$30-80", "Corporate gift market"),
            ("Personalized Ornaments", 2, "$30-80", "Christmas + year-round"),
            ("Custom Address Stamps", 2, "$40-120", "Address stamps, logo stamps"),
            ("Monogrammed Towels", 1, "$40-120", "Hotel-style personalization"),
            ("Custom Song Lyrics Art", 2, "$40-120", "First dance song prints"),
            ("Personalized Keychains", 1, "$20-60", "Leather or metal, engraved"),
            ("Custom Phone Wallpapers", 1, "$20-60", "Digital personalized art"),
            ("Engraved Whiskey Glasses", 2, "$40-120", "Groomsmen gift staple"),
            ("Custom Portraits from Photo", 3, "$60-200", "Turn photos into paintings"),
            ("Personalized Notebooks", 1, "$30-80", "Name or initial embossed"),
            ("Custom Welcome Mats", 2, "$40-120", "Doormat with family name"),
            ("Engraved Watch", 2, "$80-250", "Back engraving service"),
            ("Personalized Puzzles", 2, "$40-120", "Photo puzzles, custom shapes"),
            ("Custom Neon Signs", 3, "$100-400", "LED neon for rooms/events"),
            ("Personalized Wine Labels", 1, "$20-60", "Custom labels for bottles"),
            ("Engraved Bracelets", 2, "$40-120", "Cuff or chain with text"),
            ("Custom Playing Cards", 2, "$60-200", "Photo or branded decks"),
            ("Personalized Aprons", 1, "$30-80", "Name + fun title on apron"),
            ("Custom Coasters (Photo)", 2, "$30-80", "Resin or tile with images"),
            ("Engraved Flasks", 2, "$40-120", "Hip flask with initials"),
            ("Personalized Tote Bags", 1, "$30-80", "Name or quote printed"),
            ("Custom Bobblehead", 3, "$80-250", "3D printed from photo"),
            ("Personalized Dog Tags", 1, "$20-60", "Military style, custom text"),
        ]
    },
    "Health & Supplements": {
        "interests": ["beauty", "food"],
        "badges_pool": ["trending", "growing", "provenIncome"],
        "items": [
            ("Herbal Supplement Capsules", 3, "$200-500", "Private label ashwagandha, etc."),
            ("Protein Powder (White Label)", 3, "$300-600", "Custom flavored protein"),
            ("Vitamin Gummies", 3, "$200-500", "Private label gummy vitamins"),
            ("Essential Oil Blends", 2, "$60-200", "Therapeutic grade oils"),
            ("Probiotics", 3, "$200-500", "Gut health supplements"),
            ("Collagen Peptides", 2, "$100-300", "Beauty supplement, white label"),
            ("Melatonin Gummies", 3, "$200-500", "Sleep aid, growing demand"),
            ("Apple Cider Vinegar Gummies", 3, "$200-500", "Health trend, private label"),
            ("Electrolyte Powder", 2, "$100-300", "Hydration mix, branded"),
            ("Greens Powder", 3, "$200-500", "Superfood blends"),
            ("Magnesium Supplements", 2, "$100-300", "Sleep + recovery angle"),
            ("Turmeric Capsules", 2, "$100-300", "Anti-inflammatory supplement"),
            ("Omega-3 Fish Oil", 3, "$200-500", "Classic supplement, white label"),
            ("Biotin Gummies", 2, "$100-300", "Hair + nail growth"),
            ("Zinc Lozenges", 2, "$80-200", "Immune support seasonal seller"),
            ("Elderberry Syrup", 2, "$80-200", "Immune booster, homemade or WL"),
            ("Spirulina Powder", 2, "$80-200", "Blue-green superfood"),
            ("Mushroom Complex", 2, "$100-300", "Lions mane + reishi blend"),
            ("Fiber Supplements", 2, "$80-200", "Psyllium husk based"),
            ("Iron Supplements", 2, "$100-300", "Women's health niche"),
            ("Vitamin D Drops", 2, "$80-200", "Liquid vitamin for easy dosing"),
            ("Ashwagandha Gummies", 2, "$100-300", "Stress relief supplement"),
            ("Creatine Powder", 2, "$100-300", "Gym supplement, steady demand"),
            ("MCT Oil", 2, "$80-200", "Keto diet essential"),
            ("Digestive Enzymes", 2, "$100-300", "Gut health capsules"),
            ("Sleep Gummies", 2, "$100-300", "Melatonin + chamomile blend"),
            ("Pre-Workout Powder", 2, "$100-300", "Energy + focus formula"),
            ("Calcium Supplements", 2, "$80-200", "Bone health daily supplement"),
            ("Herbal Tea Supplements", 2, "$60-150", "Functional tea bags"),
            ("Joint Support Capsules", 2, "$100-300", "Glucosamine + turmeric blend"),
        ]
    },
    "Party & Events": {
        "interests": ["design", "crafts"],
        "badges_pool": ["fastSale", "beginner", "lowCapital"],
        "items": [
            ("Balloon Garland Kits", 1, "$40-120", "Arch kit with pump + tape"),
            ("Party Favor Bags", 1, "$20-60", "Pre-filled or empty themed"),
            ("Acrylic Cake Toppers", 2, "$30-80", "Laser cut acrylic for cakes"),
            ("Photo Booth Props", 1, "$20-60", "Printable or physical props"),
            ("Confetti Packets", 1, "$20-60", "Biodegradable tissue paper"),
            ("Banner & Bunting Sets", 1, "$20-60", "Fabric or paper letters"),
            ("Themed Tableware", 1, "$40-120", "Plates + cups + napkins set"),
            ("Gift Tags", 1, "$20-60", "Handmade or printed tags"),
            ("Wedding Favors", 2, "$60-200", "Mini candles, soaps, honey jars"),
            ("Party Hats", 1, "$20-60", "Cone hats, custom designs"),
            ("Centerpiece Kits", 2, "$40-120", "Table decor bundles"),
            ("Custom Pinatas", 2, "$40-120", "Custom shapes, number pinatas"),
            ("Guest Book Alternatives", 2, "$40-120", "Puzzle, drop frame, canvas"),
            ("LED Party Lights", 1, "$30-80", "String lights, fairy lights"),
            ("Wish Bracelets", 1, "$20-60", "Event favors with a wish"),
            ("Candy Bar Wrappers", 1, "$20-60", "Custom wrapper designs"),
            ("Paper Fans", 1, "$20-60", "Accordion fold decorations"),
            ("Number Balloons", 1, "$20-60", "Foil number + letter balloons"),
            ("Event Welcome Signs", 2, "$40-120", "Acrylic or chalkboard signs"),
            ("DIY Flower Crown Kits", 1, "$20-60", "Wire + flowers + ribbon"),
            ("Table Number Holders", 1, "$20-60", "Wire or wood number stands"),
            ("Tissue Paper Pom Poms", 1, "$20-60", "Fluffy ceiling decorations"),
            ("Cupcake Toppers", 1, "$20-60", "Themed picks for cupcakes"),
            ("Party Bags Filler Kits", 1, "$30-80", "Pre-packed goodie bag contents"),
            ("Reusable Fabric Banners", 2, "$30-80", "Washable party banners"),
            ("Themed Straws Pack", 1, "$20-60", "Paper straws with prints"),
            ("Foil Curtain Backdrop", 1, "$20-60", "Metallic photo backdrop"),
            ("Honeycomb Balls", 1, "$20-60", "Tissue paper hanging decor"),
            ("Cookie Cutter Party Sets", 1, "$30-80", "Themed baking sets"),
            ("Sparkler Tags", 1, "$20-60", "Wedding send-off sparkler holders"),
        ]
    },
    "Travel & Lifestyle": {
        "interests": ["fashion", "home"],
        "badges_pool": ["trending", "fastSale", "growing"],
        "items": [
            ("Passport Holders", 1, "$30-80", "Leather or vegan leather covers"),
            ("Luggage Tags", 1, "$20-60", "Personalized travel ID tags"),
            ("Travel Jewelry Cases", 1, "$30-80", "Compact organizer pouches"),
            ("Packing Cubes", 1, "$30-80", "Compression cubes for suitcases"),
            ("Toiletry Bags", 1, "$30-80", "Waterproof travel wash bags"),
            ("Travel Pillows", 1, "$30-80", "Memory foam neck support"),
            ("Travel Adapters", 1, "$30-80", "Universal plug adapters"),
            ("Travel Journals", 1, "$20-60", "Guided trip journals"),
            ("Fanny Packs", 1, "$30-80", "Crossbody belt bags trending"),
            ("Weekender Bags", 2, "$80-250", "Canvas or leather duffels"),
            ("Eye Masks", 1, "$20-60", "Silk sleep masks for flights"),
            ("Compression Socks", 1, "$20-60", "Flight comfort accessories"),
            ("Travel Bottles Set", 1, "$20-60", "TSA-approved refillables"),
            ("Cable Organizer Pouch", 1, "$20-60", "Tech travel case"),
            ("Laptop Backpack", 2, "$60-200", "Anti-theft travel backpack"),
            ("Travel Cutlery Set", 1, "$20-60", "Portable utensils in case"),
            ("Waterproof Phone Pouch", 1, "$20-60", "Beach and pool essential"),
            ("Travel First Aid Kit", 1, "$20-60", "Mini medical essentials"),
            ("Insulated Lunch Bag", 1, "$20-60", "Cooler bag for commuters"),
            ("Travel Document Wallet", 1, "$30-80", "Family passport organizer"),
            ("Crossbody Sling Bag", 2, "$40-120", "Minimalist everyday carry"),
            ("Packable Rain Jacket", 2, "$60-200", "Folds into pocket size"),
            ("Travel Laundry Bag", 1, "$20-60", "Dirty clothes separator"),
            ("Headphone Case", 1, "$20-60", "Hard shell earbuds case"),
            ("Money Belt", 1, "$20-60", "Hidden security waist pouch"),
            ("Travel Blanket", 1, "$30-80", "Compact fleece for planes"),
            ("Shoe Bags", 1, "$20-60", "Drawstring shoe organizers"),
            ("Camera Strap", 2, "$30-80", "Leather or woven camera straps"),
            ("Sunglasses Case", 1, "$20-60", "Hard shell with cleaning cloth"),
            ("Travel Clothesline", 1, "$20-60", "Retractable elastic line"),
        ]
    },
    "Automotive & Tools": {
        "interests": ["tech"],
        "badges_pool": ["trending", "provenIncome", "fastSale"],
        "items": [
            ("Car Phone Mount", 1, "$20-60", "Magnetic or clamp mounts"),
            ("Car Air Freshener", 1, "$20-60", "Essential oil diffuser clips"),
            ("Steering Wheel Cover", 1, "$30-80", "Leather wraps, custom fit"),
            ("Car Seat Organizer", 1, "$20-60", "Back seat storage pockets"),
            ("Dash Cam", 2, "$60-200", "White label dual camera"),
            ("Car Cleaning Kit", 1, "$30-80", "Microfiber + spray bundle"),
            ("Tire Pressure Gauge", 1, "$20-60", "Digital gauge, branded"),
            ("Emergency Car Kit", 2, "$40-120", "Jumper + flashlight + tools"),
            ("Car Trash Can", 1, "$20-60", "Leak-proof small bin"),
            ("Sunshade Windshield Cover", 1, "$20-60", "UV protection, custom fit"),
            ("Car Charger", 1, "$20-60", "Dual USB fast charger"),
            ("License Plate Frame", 1, "$20-60", "Custom design frames"),
            ("Trunk Organizer", 1, "$30-80", "Collapsible cargo storage"),
            ("Car Seat Cushion", 1, "$30-80", "Memory foam comfort pad"),
            ("LED Interior Lights", 1, "$20-60", "Color changing strip kits"),
            ("Car Window Tint Kit", 2, "$40-120", "DIY tinting films"),
            ("Garage Tool Organizer", 2, "$40-120", "Wall mount tool racks"),
            ("Magnetic Wristband", 1, "$20-60", "Hold screws while working"),
            ("Pocket Multitool", 2, "$30-80", "Compact folding tool"),
            ("Headlight Restoration Kit", 1, "$20-60", "Polish + seal kit"),
            ("Car Floor Mats", 1, "$30-80", "Custom fit rubber mats"),
            ("Steering Wheel Desk", 1, "$20-60", "Clip-on eating tray for car"),
            ("Car Gap Filler", 1, "$20-60", "Seat side crevice blocker"),
            ("Car Back Seat Mirror", 1, "$20-60", "Baby mirror for rear facing"),
            ("Garage Parking Sensor", 1, "$30-80", "Laser guide for parking"),
            ("Car Visor Organizer", 1, "$20-60", "Document holder for visor"),
            ("Tire Inflator Portable", 2, "$40-120", "12V mini air compressor"),
            ("Car Key Signal Blocker", 1, "$20-60", "Faraday pouch for fobs"),
            ("Windshield Repair Kit", 1, "$20-60", "DIY chip repair resin"),
            ("Car Bluetooth Adapter", 1, "$20-60", "AUX to bluetooth converter"),
        ]
    },
    "Candles & Fragrance": {
        "interests": ["home", "crafts"],
        "badges_pool": ["trending", "beginner", "lowCapital", "provenIncome"],
        "items": [
            ("Coconut Wax Candles", 2, "$60-180", "Cleaner burn than soy"),
            ("Wooden Wick Candles", 2, "$60-180", "Crackling sound sells experience"),
            ("Candle Gift Sets", 2, "$80-250", "Curated 3-pack bundles"),
            ("Car Fragrance Diffusers", 1, "$20-60", "Essential oil car clips"),
            ("Wax Melt Gift Sets", 1, "$30-100", "Seasonal scent collections"),
            ("Pillar Candles", 2, "$40-120", "Sculptural decorative candles"),
            ("Scented Drawer Liners", 1, "$20-60", "Fragrant paper for drawers"),
            ("Candle Refill Kits", 1, "$30-80", "Eco refills for existing jars"),
            ("Floating Candles", 2, "$40-120", "Event and spa decor"),
            ("Taper Candles", 2, "$40-120", "Dinner table essentials"),
            ("Birthday Cake Candles", 1, "$20-60", "Number and novelty candles"),
            ("Massage Candles", 2, "$40-120", "Melt into massage oil"),
            ("Gel Candles", 2, "$40-120", "Clear gel with embeds"),
            ("Candle Making Workshops", 2, "$60-200", "Sell experience kits by mail"),
            ("Essential Oil Diffuser Blends", 1, "$30-80", "Pre-mixed oil bottles"),
            ("Linen Spray", 1, "$20-60", "Pillow and sheet mist"),
            ("Wardrobe Fresheners", 1, "$20-60", "Cedar or lavender sachets"),
            ("Candle Subscription Box", 2, "$80-250", "Monthly new scent delivered"),
            ("Decorative Match Bottles", 1, "$20-60", "Colored tips in glass jar"),
            ("Aroma Beads", 1, "$20-60", "Scented beads for cars and closets"),
            ("Beeswax Candles", 2, "$60-180", "Natural honey scent candles"),
            ("Candle Tins", 1, "$30-80", "Travel-sized tin candles"),
            ("Flameless LED Candles", 1, "$30-80", "Battery candles for safety"),
            ("Candle Wick Trimmers", 1, "$20-60", "Brass wick cutting tool"),
            ("Wax Melt Burners", 2, "$40-120", "Ceramic or electric warmers"),
            ("Scented Pinecones", 1, "$20-60", "Cinnamon coated fall decor"),
            ("Room Diffuser Oils", 1, "$30-80", "Refill oils for reed diffusers"),
            ("Car Vent Freshener", 1, "$20-60", "Clip-on scented stones"),
            ("Candle Safety Kit", 1, "$20-60", "Snuffer + trimmer + dipper set"),
            ("Scented Wax Tablets", 1, "$20-60", "Decorative hanging wax"),
        ]
    },
    "Handmade Leather Goods": {
        "interests": ["fashion", "crafts"],
        "badges_pool": ["trending", "provenIncome", "lessCrowded"],
        "items": [
            ("Leather Wallets", 3, "$100-300", "Bifold and card holders"),
            ("Leather Journal Covers", 2, "$60-200", "Refillable notebook covers"),
            ("Leather Tote Bags", 3, "$100-400", "Full grain leather totes"),
            ("Leather Watch Bands", 2, "$40-120", "Apple Watch straps handmade"),
            ("Leather Dopp Kit", 2, "$60-200", "Men's toiletry bag"),
            ("Leather Card Holder", 2, "$40-120", "Slim front pocket wallet"),
            ("Leather Laptop Sleeve", 2, "$60-200", "Padded leather sleeve"),
            ("Leather Desk Pad", 2, "$80-250", "Premium desk protector"),
            ("Leather Catch-All Tray", 2, "$30-80", "Snap corner valet tray"),
            ("Leather Bookmark", 1, "$20-60", "Stamped or embossed"),
            ("Leather Camera Bag", 3, "$100-300", "Padded DSLR messenger bag"),
            ("Leather Suspenders", 2, "$40-120", "Vintage style braces"),
            ("Leather Wine Carrier", 2, "$40-120", "Single bottle holder"),
            ("Leather Glasses Case", 2, "$30-80", "Hard or soft eyewear case"),
            ("Leather Coin Pouch", 1, "$20-60", "Small snap or zip pouch"),
            ("Leather Luggage Tag", 1, "$20-60", "Monogrammed travel tags"),
            ("Leather Pen Case", 2, "$30-80", "Roll-up pen holder"),
            ("Leather Dog Collar", 2, "$40-120", "Personalized pet collars"),
            ("Leather Coaster Set", 2, "$30-80", "Stamped round coasters"),
            ("Leather Apron", 3, "$80-250", "Workshop or barista apron"),
            ("Leather Passport Cover", 2, "$30-80", "Stamped travel document holder"),
            ("Leather Cord Organizer", 1, "$20-60", "Cable wrap with snap"),
            ("Leather Flask", 2, "$40-120", "Stainless wrapped in leather"),
            ("Leather Photo Album", 3, "$80-250", "Wedding album cover"),
            ("Leather Mouse Pad", 2, "$30-80", "Full grain desk pad"),
            ("Leather AirTag Case", 1, "$20-60", "Keychain tracker holder"),
            ("Leather Belt Bag", 2, "$60-200", "Hip belt purse"),
            ("Leather Headband", 1, "$20-60", "Knotted leather hair band"),
            ("Leather Pouch Bag", 2, "$40-120", "Drawstring or zip pouch"),
            ("Leather Ring Holder", 1, "$20-60", "Cone shaped ring display"),
        ]
    },
    "Woodworking & Carpentry": {
        "interests": ["crafts", "home"],
        "badges_pool": ["trending", "provenIncome", "lessCrowded"],
        "items": [
            ("Wooden Ring Boxes", 2, "$40-120", "Proposal ring box, walnut"),
            ("Wooden Phone Dock", 2, "$30-80", "Charging station from hardwood"),
            ("Wooden Serving Board", 2, "$60-200", "Charcuterie boards sell well"),
            ("Wooden Crate Shelves", 2, "$40-120", "Rustic wall storage"),
            ("Wooden Toy Cars", 2, "$30-80", "Natural finish kids toys"),
            ("Wooden Cribbage Board", 2, "$40-120", "Game board with pegs"),
            ("Wooden Name Puzzle", 2, "$40-120", "Kids name puzzles, custom"),
            ("Wooden Coasters", 1, "$20-60", "Sliced wood with bark edge"),
            ("Wooden Utensil Set", 2, "$40-120", "Spoons, spatulas, ladles"),
            ("Wooden Picture Frame", 2, "$30-80", "Handmade from reclaimed wood"),
            ("Wooden Dice Set", 2, "$30-80", "Oversized yard dice game"),
            ("Wooden Key Holder", 2, "$30-80", "Wall mount key rack"),
            ("Wooden Wine Rack", 2, "$60-200", "Countertop bottle storage"),
            ("Wooden Jewelry Stand", 2, "$40-120", "Tree-shaped earring holder"),
            ("Wooden Plant Stand", 2, "$40-120", "Multi-tier plant display"),
            ("Wooden Recipe Box", 2, "$30-80", "Card file for recipes"),
            ("Wooden Chess Set", 3, "$80-250", "Handcarved pieces + board"),
            ("Wooden Wall Hooks", 1, "$20-60", "Peg hooks for entry"),
            ("Wooden Laptop Riser", 2, "$40-120", "Desk ergonomic stand"),
            ("Wooden Candle Holder Set", 2, "$30-80", "Tiered tea light holders"),
            ("Wooden Business Card Holder", 2, "$30-80", "Desk card display"),
            ("Wooden Letter Rack", 2, "$30-80", "Mail organizer for entry"),
            ("Wooden Earring Display", 2, "$30-80", "Craft show display stands"),
            ("Wooden Desk Caddy", 2, "$40-120", "Pen and supply organizer"),
            ("Wooden Tic-Tac-Toe Board", 1, "$20-60", "Coffee table game"),
            ("Wooden Towel Rack", 2, "$40-120", "Bathroom ladder rack"),
            ("Wooden Tablet Stand", 2, "$30-80", "Kitchen recipe holder"),
            ("Wooden Coat Rack", 2, "$40-120", "Entryway peg rack"),
            ("Wooden Napkin Holder", 1, "$20-60", "Table counter holder"),
            ("Wooden Doorstop", 1, "$20-60", "Wedge or animal shape"),
        ]
    },
    "Printables & POD": {
        "interests": ["design"],
        "badges_pool": ["beginner", "lowCapital", "fastSale"],
        "items": [
            ("Wall Art Prints", 1, "$20-60", "Digital download art prints"),
            ("Wedding Invitation Suite", 2, "$40-120", "Editable templates"),
            ("Meal Planner Printable", 1, "$20-60", "Weekly meal planning sheets"),
            ("Budget Tracker Printable", 1, "$20-60", "Monthly budget worksheets"),
            ("Baby Shower Games", 1, "$20-60", "Printable party games bundle"),
            ("Teacher Worksheets", 1, "$20-60", "Grade-specific activity sheets"),
            ("Affirmation Cards", 1, "$20-60", "Daily positive affirmation deck"),
            ("Habit Tracker Printable", 1, "$20-60", "Monthly habit grid sheets"),
            ("Birthday Party Kit", 1, "$20-60", "Invites + banner + tags"),
            ("Chore Chart for Kids", 1, "$20-60", "Editable weekly chart"),
            ("POD Mugs", 1, "$30-80", "Print-on-demand custom mugs"),
            ("POD Throw Pillows", 1, "$30-80", "Custom design pillows"),
            ("POD Phone Cases", 1, "$20-60", "Custom artwork phone cases"),
            ("POD Tote Bags", 1, "$20-60", "Custom print canvas bags"),
            ("POD Posters", 1, "$20-60", "Large format art prints"),
            ("POD Notebooks", 1, "$20-60", "Custom cover notebooks"),
            ("POD Stickers", 1, "$20-60", "Die-cut custom stickers"),
            ("POD Puzzles", 1, "$30-80", "Custom photo jigsaw puzzles"),
            ("POD Blankets", 2, "$40-120", "Photo or pattern blankets"),
            ("POD Ornaments", 1, "$20-60", "Custom holiday ornaments"),
            ("POD Shower Curtains", 1, "$30-80", "Art shower curtains"),
            ("POD Aprons", 1, "$20-60", "Funny quote aprons"),
            ("POD Pet Bandanas", 1, "$20-60", "Custom dog bandanas"),
            ("POD Coasters", 1, "$20-60", "Photo or art coasters"),
            ("POD Canvas Art", 2, "$40-120", "Gallery wrapped prints"),
            ("POD Yard Signs", 1, "$20-60", "Celebration and event signs"),
            ("POD Magnets", 1, "$20-60", "Fridge magnets custom designs"),
            ("POD Keychains", 1, "$20-60", "Acrylic photo keychains"),
            ("POD Socks", 1, "$20-60", "All-over print socks"),
            ("POD Face Masks", 1, "$20-60", "Custom print fabric masks"),
        ]
    },
    "Vintage & Upcycled": {
        "interests": ["fashion", "home"],
        "badges_pool": ["trending", "lessCrowded", "growing"],
        "items": [
            ("Vintage Denim Resale", 2, "$60-200", "Thrift and flip Levis"),
            ("Upcycled Furniture", 3, "$100-400", "Paint and refinish finds"),
            ("Vintage Jewelry Resale", 2, "$40-120", "Estate sale treasure hunts"),
            ("Upcycled Glass Bottles", 1, "$20-60", "Lamps and vases from bottles"),
            ("Vintage Book Resale", 1, "$20-60", "First editions and rare finds"),
            ("Upcycled Pallet Furniture", 3, "$60-200", "Shelves and tables from pallets"),
            ("Vintage Camera Resale", 2, "$60-200", "Film cameras making comeback"),
            ("Upcycled Tire Products", 2, "$40-120", "Planters and ottomans"),
            ("Vintage Vinyl Records", 1, "$20-60", "Record collecting is booming"),
            ("Upcycled Map Art", 1, "$20-60", "Cut maps into wall art"),
            ("Vintage Kitchenware", 1, "$20-60", "Pyrex and cast iron resale"),
            ("Upcycled Fabric Scraps", 1, "$20-60", "Patchwork items from remnants"),
            ("Vintage Poster Prints", 1, "$20-60", "Retro ad reproduction"),
            ("Upcycled Tin Can Planters", 1, "$20-60", "Painted can herb gardens"),
            ("Vintage Toy Resale", 2, "$40-120", "Nostalgia toys for collectors"),
            ("Upcycled Suitcase Tables", 2, "$60-200", "Vintage luggage side tables"),
            ("Vintage Clothing Resale", 2, "$60-200", "90s and Y2K fashion"),
            ("Upcycled Wine Cork Crafts", 1, "$20-60", "Boards and trivets"),
            ("Vintage Sign Replicas", 2, "$40-120", "Metal retro advertising signs"),
            ("Upcycled Sweater Mittens", 1, "$20-60", "Cut old sweaters into mittens"),
            ("Vintage Watch Resale", 2, "$80-250", "Seiko and Casio classics"),
            ("Upcycled Jean Bags", 2, "$40-120", "Totes from old denim"),
            ("Vintage Brooch Resale", 1, "$20-60", "Estate sale costume jewelry"),
            ("Upcycled T-Shirt Quilts", 3, "$60-200", "Memory quilts from old tees"),
            ("Vintage Typewriter Resale", 2, "$60-200", "Working typewriters trending"),
            ("Upcycled Window Frames", 2, "$30-80", "Frames into photo displays"),
            ("Vintage Board Game Resale", 1, "$20-60", "Complete retro games"),
            ("Upcycled Ladder Shelves", 2, "$40-120", "Old ladders as bookcases"),
            ("Vintage Hat Resale", 1, "$20-60", "Fedoras and cowboy hats"),
            ("Upcycled Book Safes", 1, "$20-60", "Hollowed book storage boxes"),
        ]
    },
}

# ============================================================
# SAAS PRODUCT SEEDS — 200 ideas
# ============================================================

SAAS_CATEGORIES = {
    "AI & Automation Tools": {
        "interests": ["ai", "tech"],
        "badges_pool": ["trending", "growing", "provenIncome"],
        "items": [
            ("AI Resume Builder", 3, "$100-400", "Upload resume, get optimized version"),
            ("AI Email Writer", 2, "$50-200", "Cold email generator for sales teams"),
            ("AI Meeting Notes", 3, "$100-400", "Record calls, get action items"),
            ("AI Blog Post Generator", 2, "$50-200", "Topic in, SEO article out"),
            ("AI Code Reviewer", 3, "$200-600", "Automated PR reviews for devs"),
            ("AI Customer Support Bot", 3, "$200-600", "Train on your docs, deploy chat"),
            ("AI Social Caption Writer", 2, "$50-200", "Brand voice captions in seconds"),
            ("AI Product Description Writer", 2, "$50-200", "Ecommerce listing optimizer"),
            ("AI Image Background Remover", 2, "$50-200", "Product photo cleanup tool"),
            ("AI Podcast Show Notes", 2, "$50-200", "Audio in, blog + quotes out"),
            ("AI Invoice Parser", 3, "$100-400", "Scan invoices, extract data"),
            ("AI Diet Plan Generator", 2, "$100-300", "Personalized meal plans from goals"),
            ("AI Logo Generator", 2, "$100-300", "Text prompt to logo concepts"),
            ("AI Video Subtitler", 2, "$50-200", "Auto-caption any video file"),
            ("AI Pricing Optimizer", 3, "$200-600", "Dynamic pricing from market data"),
            ("AI Proposal Writer", 3, "$100-400", "Client brief to polished proposal"),
            ("AI Flashcard Maker", 2, "$50-200", "PDF or notes to study cards"),
            ("AI Recipe Generator", 2, "$50-200", "Ingredients in, meals out"),
            ("AI Legal Doc Analyzer", 3, "$200-600", "Contract review and flagging"),
            ("AI Workout Planner", 2, "$100-300", "Goals + equipment = plan"),
        ]
    },
    "Chrome Extensions": {
        "interests": ["tech"],
        "badges_pool": ["trending", "beginner", "fastSale", "lowCapital"],
        "items": [
            ("Tab Manager Extension", 2, "$50-200", "Group, save, restore tab sessions"),
            ("Price Tracker Extension", 2, "$50-200", "Amazon price history alerts"),
            ("Screenshot & Annotate", 2, "$50-200", "Capture + markup + share"),
            ("Email Tracker Extension", 2, "$50-200", "Know when emails are opened"),
            ("Bookmark Manager Pro", 2, "$50-200", "Visual bookmarks with tags"),
            ("Focus Timer Extension", 1, "$30-100", "Pomodoro + site blocking"),
            ("Grammar Checker", 3, "$100-400", "AI writing assistant in browser"),
            ("Color Picker Extension", 1, "$30-100", "Pick colors from any webpage"),
            ("Social Media Scheduler", 2, "$50-200", "Queue posts from any page"),
            ("Coupon Finder Extension", 2, "$50-200", "Auto-apply discount codes"),
            ("Dark Mode Everywhere", 1, "$30-100", "Force dark mode on any site"),
            ("Reader Mode Extension", 1, "$30-100", "Clean article reading view"),
            ("Password Generator", 1, "$30-100", "Secure passwords one click away"),
            ("Text-to-Speech Extension", 2, "$50-200", "Read articles aloud"),
            ("Video Speed Controller", 1, "$30-100", "Speed up any HTML5 video"),
            ("New Tab Dashboard", 2, "$50-200", "Productivity dashboard on new tab"),
            ("Clipboard Manager", 2, "$50-200", "History of everything you copy"),
            ("SEO Analyzer Extension", 2, "$100-300", "Quick page SEO metrics"),
            ("Email Unsubscriber", 2, "$50-200", "One-click unsubscribe from lists"),
            ("Website Blocker", 1, "$30-100", "Block distracting sites by schedule"),
        ]
    },
    "Micro SaaS Tools": {
        "interests": ["tech"],
        "badges_pool": ["trending", "growing", "provenIncome"],
        "items": [
            ("Invoice Generator", 2, "$50-200", "Create and send invoices fast"),
            ("Link-in-Bio Tool", 2, "$50-200", "Custom bio link pages"),
            ("QR Code Generator", 1, "$20-80", "Dynamic QR codes with analytics"),
            ("Email Signature Builder", 1, "$30-100", "Professional signatures in minutes"),
            ("Waitlist Page Builder", 1, "$30-100", "Launch page + email collection"),
            ("Testimonial Collector", 2, "$50-200", "Collect and display social proof"),
            ("Appointment Scheduler", 2, "$100-300", "Calendly alternative for niches"),
            ("Form Builder", 2, "$100-300", "Typeform-like but cheaper"),
            ("URL Shortener", 1, "$20-80", "Custom short links with tracking"),
            ("Habit Tracker App", 2, "$50-200", "Daily streak tracker"),
            ("Digital Business Card", 1, "$30-100", "NFC + QR contact sharing"),
            ("Simple CRM", 3, "$100-400", "Lightweight CRM for freelancers"),
            ("Time Tracker", 2, "$50-200", "Log hours, generate reports"),
            ("Poll & Survey Tool", 2, "$50-200", "Quick polls for teams or public"),
            ("Changelog Tool", 1, "$30-100", "Public product updates page"),
            ("Status Page Builder", 1, "$30-100", "Uptime monitoring + public status"),
            ("Feedback Widget", 2, "$50-200", "Embed feedback button on any site"),
            ("RSS Feed Reader", 2, "$50-200", "Modern feed reader for power users"),
            ("File Sharing Tool", 2, "$50-200", "Simple file transfer, no signup"),
            ("Kanban Board", 2, "$50-200", "Trello alternative for small teams"),
        ]
    },
    "Content & Marketing Tools": {
        "interests": ["tech", "design"],
        "badges_pool": ["trending", "growing", "fastSale"],
        "items": [
            ("Social Post Scheduler", 3, "$100-400", "Schedule posts across platforms"),
            ("SEO Keyword Tracker", 3, "$100-400", "Track rankings over time"),
            ("Email Newsletter Tool", 3, "$100-400", "Simple newsletters for creators"),
            ("Landing Page Builder", 3, "$100-400", "No-code pages that convert"),
            ("Podcast Hosting Platform", 3, "$200-600", "Host + distribute + analytics"),
            ("Content Calendar Tool", 2, "$50-200", "Plan content across channels"),
            ("Hashtag Generator", 1, "$30-100", "Best hashtags for any niche"),
            ("Bio Link Analytics", 2, "$50-200", "Track clicks on bio links"),
            ("A/B Testing Tool", 3, "$100-400", "Test headlines, CTAs, layouts"),
            ("Influencer Outreach Tool", 3, "$100-400", "Find and email influencers"),
            ("Social Proof Widget", 2, "$50-200", "Show recent purchases popup"),
            ("Blog Comment Manager", 2, "$50-200", "Moderate + reply to blog comments"),
            ("Affiliate Tracking Tool", 3, "$100-400", "Track affiliate links + payouts"),
            ("Video Thumbnail Maker", 2, "$50-200", "YouTube thumbnail templates"),
            ("Content Repurposer", 2, "$100-300", "Blog to social to newsletter"),
            ("Competitor Monitor", 3, "$100-400", "Track competitor site changes"),
            ("Review Management Tool", 2, "$100-300", "Aggregate and respond to reviews"),
            ("UTM Builder & Tracker", 1, "$30-100", "Create and track UTM parameters"),
            ("Lead Magnet Delivery", 2, "$50-200", "Email gate + PDF delivery"),
            ("Social Listening Tool", 3, "$200-600", "Monitor brand mentions everywhere"),
        ]
    },
    "Developer Tools": {
        "interests": ["tech"],
        "badges_pool": ["trending", "growing", "lessCrowded"],
        "items": [
            ("API Monitoring Service", 3, "$100-400", "Uptime + latency tracking"),
            ("Error Tracking Tool", 3, "$200-600", "Sentry alternative for indie devs"),
            ("Database GUI Tool", 3, "$100-400", "Visual DB management"),
            ("Webhook Testing Tool", 2, "$50-200", "Inspect and debug webhooks"),
            ("Cron Job Manager", 2, "$50-200", "Schedule and monitor cron jobs"),
            ("Environment Variable Manager", 2, "$50-200", "Secure env vars for teams"),
            ("API Documentation Builder", 2, "$100-300", "Beautiful API docs from spec"),
            ("Log Aggregator", 3, "$200-600", "Centralized logging for small teams"),
            ("Feature Flag Service", 3, "$100-400", "Toggle features without deploys"),
            ("Code Snippet Manager", 2, "$50-200", "Searchable code snippet library"),
            ("SSL Certificate Monitor", 1, "$30-100", "Alert before certs expire"),
            ("Docker Dashboard", 3, "$100-400", "Visual container management"),
            ("Git Commit Analyzer", 2, "$50-200", "Team productivity insights from git"),
            ("Regex Tester Tool", 1, "$30-100", "Visual regex builder and tester"),
            ("IP Geolocation API", 2, "$50-200", "IP to location data service"),
            ("Markdown Editor", 2, "$50-200", "Collaborative markdown with preview"),
            ("DNS Lookup Tool", 1, "$30-100", "DNS records checker and monitor"),
            ("JSON Formatter API", 1, "$30-100", "Format + validate JSON online"),
            ("Load Testing Tool", 3, "$100-400", "Stress test your APIs"),
            ("CI/CD Pipeline Builder", 3, "$200-600", "Simple deploy pipelines"),
        ]
    },
    "Ecommerce Tools": {
        "interests": ["tech"],
        "badges_pool": ["trending", "provenIncome", "growing"],
        "items": [
            ("Product Photography Tool", 2, "$100-300", "AI background for product photos"),
            ("Shipping Calculator", 2, "$50-200", "Multi-carrier rate comparison"),
            ("Inventory Management", 3, "$100-400", "Track stock across channels"),
            ("Return Label Generator", 2, "$50-200", "Self-service returns for shops"),
            ("Product Review Widget", 2, "$50-200", "Collect + display reviews"),
            ("Size Guide Builder", 1, "$30-100", "Custom size charts for stores"),
            ("Abandoned Cart Recovery", 3, "$100-400", "Email + SMS cart reminders"),
            ("Product Feed Manager", 3, "$100-400", "Sync products to marketplaces"),
            ("Price Comparison Scraper", 3, "$100-400", "Monitor competitor pricing"),
            ("Order Tracking Page", 2, "$50-200", "Branded tracking page builder"),
            ("Upsell Popup Builder", 2, "$50-200", "Post-purchase upsell offers"),
            ("Customer Loyalty Program", 3, "$100-400", "Points and rewards system"),
            ("Gift Card Generator", 2, "$50-200", "Digital gift cards for shops"),
            ("Subscription Box Manager", 3, "$200-600", "Recurring order management"),
            ("Tax Calculator", 2, "$100-300", "Sales tax for US/EU"),
            ("Supplier Directory", 2, "$100-300", "Vetted supplier database"),
            ("Dropship Automation", 3, "$200-600", "Auto-order from suppliers"),
            ("SKU Generator", 1, "$30-100", "Systematic product numbering"),
            ("Warranty Manager", 2, "$50-200", "Track and process warranties"),
            ("Packing Slip Generator", 1, "$30-100", "Branded packing slips"),
        ]
    },
    "Education & Learning": {
        "interests": ["tech", "writing"],
        "badges_pool": ["trending", "growing", "beginner"],
        "items": [
            ("Online Course Platform", 3, "$200-600", "Host and sell video courses"),
            ("Flashcard App", 2, "$50-200", "Spaced repetition learning"),
            ("Quiz Maker Tool", 2, "$50-200", "Create and share quizzes"),
            ("Tutoring Marketplace", 3, "$200-600", "Connect tutors with students"),
            ("Language Learning App", 3, "$200-600", "Niche language tools"),
            ("Study Group Platform", 2, "$100-300", "Virtual study rooms"),
            ("Homework Helper Tool", 2, "$100-300", "AI-powered homework assistance"),
            ("Certification Tracker", 2, "$50-200", "Track professional certifications"),
            ("Student Budget Planner", 1, "$30-100", "Budget app for college students"),
            ("Note-Taking App", 2, "$100-300", "Structured notes with templates"),
            ("Book Summary App", 2, "$100-300", "Non-fiction book summaries"),
            ("Skill Assessment Tool", 2, "$100-300", "Test and certify skills"),
            ("Vocabulary Builder", 2, "$50-200", "Word-a-day with context"),
            ("Math Practice App", 2, "$100-300", "Drills for K-12 math"),
            ("Writing Practice Tool", 2, "$50-200", "Daily writing prompts + feedback"),
            ("Presentation Builder", 3, "$100-400", "AI-powered slide decks"),
            ("Reading List Manager", 1, "$30-100", "Track and share book lists"),
            ("Teacher Resource Hub", 2, "$100-300", "Lesson plans + worksheets"),
            ("Code Learning Platform", 3, "$200-600", "Interactive coding challenges"),
            ("Parent Communication App", 2, "$100-300", "School-to-parent updates"),
        ]
    },
    "Productivity & Collaboration": {
        "interests": ["tech"],
        "badges_pool": ["trending", "provenIncome", "growing"],
        "items": [
            ("Team Standup Bot", 2, "$50-200", "Async standups via Slack/Discord"),
            ("OKR Tracking Tool", 2, "$100-300", "Goals and key results tracker"),
            ("Meeting Agenda Builder", 1, "$30-100", "Structured agendas with notes"),
            ("Document Signer", 3, "$100-400", "E-signatures for small biz"),
            ("Knowledge Base Builder", 2, "$100-300", "Internal wiki for teams"),
            ("Retrospective Tool", 2, "$50-200", "Sprint retros with voting"),
            ("Employee Onboarding", 3, "$100-400", "Checklist-based onboarding flows"),
            ("1-on-1 Meeting Tool", 2, "$50-200", "Track topics and action items"),
            ("Team Directory", 1, "$30-100", "Internal people directory"),
            ("Decision Log Tool", 1, "$30-100", "Record and search past decisions"),
            ("Shared Inbox Tool", 3, "$100-400", "Team email collaboration"),
            ("Async Video Messages", 2, "$50-200", "Loom alternative for teams"),
            ("Team Mood Tracker", 1, "$30-100", "Weekly pulse surveys"),
            ("SOPs Manager", 2, "$50-200", "Standard operating procedures hub"),
            ("Brainstorming Tool", 2, "$50-200", "Digital whiteboard with voting"),
            ("Resource Scheduler", 2, "$100-300", "Book rooms, equipment, people"),
            ("Weekly Report Generator", 2, "$50-200", "Auto-compile team updates"),
            ("Goal Tracking Dashboard", 2, "$50-200", "Personal + team goals"),
            ("Task Delegation Tool", 2, "$50-200", "Assign + track delegated work"),
            ("Remote Work Dashboard", 2, "$100-300", "Working hours + availability"),
        ]
    },
    "Finance & Business Tools": {
        "interests": ["tech"],
        "badges_pool": ["trending", "provenIncome", "growing"],
        "items": [
            ("Expense Tracker App", 2, "$50-200", "Receipt scanning + categories"),
            ("Budget Planner", 2, "$50-200", "Monthly budget with forecasting"),
            ("Freelance Contract Generator", 2, "$50-200", "Template contracts for gigs"),
            ("Profit Calculator", 1, "$30-100", "Product margins made simple"),
            ("Payment Link Generator", 2, "$100-300", "Stripe-powered payment links"),
            ("Financial Dashboard", 3, "$100-400", "Multi-account money overview"),
            ("Tax Prep Organizer", 2, "$100-300", "Organize docs before tax time"),
            ("Subscription Manager", 2, "$50-200", "Track all your subscriptions"),
            ("Business Name Generator", 1, "$30-100", "AI naming + domain check"),
            ("Cashflow Forecaster", 3, "$100-400", "Predict cash position ahead"),
            ("Receipt Scanner", 2, "$50-200", "Photo to expense entry"),
            ("Pricing Page Builder", 1, "$30-100", "Beautiful pricing table generator"),
            ("Payroll Calculator", 2, "$100-300", "Simple payroll for small teams"),
            ("Client Portal", 3, "$100-400", "Share files + invoices with clients"),
            ("Equity Calculator", 2, "$50-200", "Startup equity split tool"),
            ("Grant Finder Tool", 2, "$100-300", "Discover relevant business grants"),
            ("Mileage Tracker", 1, "$30-100", "GPS-based trip logging"),
            ("W-9 Generator", 1, "$30-100", "Auto-fill tax forms"),
            ("Proposal Template Builder", 2, "$50-200", "Professional proposals fast"),
            ("Business Plan Generator", 2, "$100-300", "Guided business plan builder"),
        ]
    },
    "Community & Membership": {
        "interests": ["tech"],
        "badges_pool": ["trending", "growing", "provenIncome"],
        "items": [
            ("Paid Newsletter Platform", 2, "$50-200", "Substack alternative for niches"),
            ("Membership Community App", 3, "$100-400", "Gated content + discussions"),
            ("Discord Bot Builder", 2, "$50-200", "Custom bots without coding"),
            ("Event Ticketing Platform", 3, "$100-400", "Sell tickets to events"),
            ("Online Forum Builder", 2, "$100-300", "Modern forum for communities"),
            ("Creator Tip Jar", 1, "$30-100", "Accept tips from fans"),
            ("Podcast Community Hub", 2, "$100-300", "Listener community platform"),
            ("Coaching Platform", 3, "$100-400", "Schedule + deliver coaching"),
            ("Alumni Network Tool", 2, "$100-300", "Stay connected post-graduation"),
            ("Virtual Meetup Platform", 3, "$100-400", "Video meetups with scheduling"),
            ("Challenge Platform", 2, "$50-200", "30-day challenges for groups"),
            ("Fan Club Manager", 2, "$50-200", "Manage paid fan communities"),
            ("Book Club Platform", 2, "$50-200", "Organize reading groups online"),
            ("Mastermind Group Tool", 2, "$100-300", "Structured peer groups"),
            ("Local Business Directory", 2, "$100-300", "Niche directories for cities"),
            ("Marketplace Builder", 3, "$200-600", "Two-sided marketplace platform"),
            ("Job Board Builder", 2, "$100-300", "Niche job boards for industries"),
            ("Mentorship Matching Tool", 3, "$100-400", "Connect mentors + mentees"),
            ("Online Retreat Platform", 3, "$200-600", "Virtual wellness retreats"),
            ("Accountability Partner App", 2, "$50-200", "Match and track accountability"),
        ]
    },
}

# ============================================================
# BREAKDOWN TEMPLATES — Category-specific coach language
# ============================================================

def make_breakdown(name, deck, capital, effort, category):
    """Generate a realistic breakdown with category-specific language."""
    cap_nums = [int(x) for x in capital.replace("$", "").replace(",", "").split("-")]
    low, high = cap_nums[0], cap_nums[1] if len(cap_nums) > 1 else cap_nums[0] * 3
    mid = (low + high) // 2

    margin_pct = random.randint(40, 85)
    monthly_low = random.randint(300, 1500)
    monthly_high = monthly_low * random.randint(2, 4)

    effort_map = {1: "a few hours a week", 2: "part-time effort", 3: "real commitment"}
    effort_desc = effort_map.get(effort, "part-time effort")

    if deck == "physical":
        return {
            "strategy": {
                "body": f"Here's the play with <strong>{name}</strong>: you're not just selling a product. You're selling a solution to a specific problem. Find the one angle that makes yours different from everyone else's. Maybe it's the ingredient, the design, or the story behind it. <strong>Own that one angle hard.</strong>",
                "action": f"Define your unique angle for {name}"
            },
            "value": {
                "body": f"Your buyer is someone who's already looking for this. They're comparing 5-10 options right now. Your job is to make the decision easy. <strong>Clear photos, honest description, one reason to pick you.</strong> That's it.",
                "action": "Write a 1-line description of your ideal buyer"
            },
            "profit": {
                "body": f"Cost to source: roughly <strong>${low}-{mid}</strong> for your first batch. Sell each unit for 2-3x your cost. After platform fees and shipping, you're looking at <strong>{margin_pct}% margins</strong>. Start small, prove demand, then scale.",
                "stats": [{"label": "Margin", "value": f"{margin_pct}%"}, {"label": "Monthly potential", "value": f"${monthly_low}-{monthly_high}"}],
                "action": "Calculate your cost per unit and target price"
            },
            "distributors": {
                "body": f"Source from <strong>AliExpress</strong> for samples (ships in 7-14 days). Once validated, move to <strong>Alibaba</strong> for bulk orders at 40-60% less. In India, check <strong>IndiaMART</strong> for local manufacturers. Always order samples before committing to bulk.",
                "action": "Order 3 samples from different AliExpress suppliers"
            },
            "pricing": {
                "body": f"Three pricing tiers that work: <strong>(1) Entry</strong> at the low end to build reviews. <strong>(2) Standard</strong> at market rate once you have 10+ reviews. <strong>(3) Bundle</strong> multiple units at a slight discount to boost AOV. Start with entry pricing.",
                "action": "Set your launch price and bundle offer"
            },
            "sellingPrice": {
                "body": f"Launch at a competitive price to build traction and reviews. Once you hit 20 sales, raise prices 15-20%. <strong>Don't underprice.</strong> It attracts the wrong buyers and kills your margins.",
                "stats": [{"label": "Launch", "value": f"${mid}"}, {"label": "After 20 sales", "value": f"${int(mid * 1.2)}"}],
                "action": "List your first product at the launch price"
            }
        }
    else:  # saas
        mrr_low = random.randint(200, 2000)
        mrr_high = mrr_low * random.randint(3, 8)
        return {
            "strategy": {
                "body": f"<strong>{name}</strong> works because it solves one specific pain point really well. Don't try to be everything. Pick the #1 frustration in your target market and build the simplest possible fix. <strong>Ship fast, iterate from feedback.</strong>",
                "action": f"Define the one problem {name} solves"
            },
            "value": {
                "body": f"Your early adopters are people already using 2-3 tools duct-taped together. They'll pay for something that <strong>just works</strong>. Find them in Reddit, Twitter, and niche communities. Show them you solve their specific problem.",
                "action": "Find 3 communities where your target users hang out"
            },
            "profit": {
                "body": f"SaaS margins are <strong>80-90%</strong> once you're past the build phase. Initial investment is {effort_desc} plus <strong>${low}-{high}</strong> for hosting and tools. Revenue compounds monthly. <strong>10 paying users at $29/mo = $290 MRR.</strong>",
                "stats": [{"label": "Target MRR", "value": f"${mrr_low}-{mrr_high}"}, {"label": "Margin", "value": "80-90%"}],
                "action": "Calculate your MRR target for month 3"
            },
            "distributors": {
                "body": f"Build with <strong>Next.js + Vercel</strong> (free tier gets you started). Database: <strong>Supabase</strong> (free for < 50K rows). Payments: <strong>Stripe</strong> ($0 until you charge). Total cost to launch: potentially $0.",
                "action": "Set up your tech stack accounts"
            },
            "pricing": {
                "body": f"Start with <strong>two tiers</strong>: Free (limited) + Pro ($19-49/mo). Free tier drives signups, Pro converts the serious users. Add a Team tier later when you have demand. <strong>Annual billing at 20% discount</strong> helps cash flow.",
                "action": "Define your free vs pro feature split"
            },
            "sellingPrice": {
                "body": f"Price based on value, not cost. If you save someone 5 hours/month, that's worth $50+. Start at <strong>$19/mo</strong> for individuals, <strong>$49/mo</strong> for teams. Raise prices after 100 customers (grandfather existing).",
                "stats": [{"label": "Individual", "value": "$19/mo"}, {"label": "Team", "value": "$49/mo"}],
                "action": "Set your launch pricing and publish it"
            }
        }


def make_id(name):
    return name.lower().replace("&", "and").replace("(", "").replace(")", "").replace("/", "-").replace(" ", "-").replace("--", "-").strip("-")


def make_badges(pool):
    count = random.randint(1, 3)
    return random.sample(pool, min(count, len(pool)))


# ============================================================
# GENERATE ALL IDEAS
# ============================================================

def generate_all():
    physical_ideas = []
    saas_ideas = []

    # Physical products
    for cat_name, cat_data in PHYSICAL_CATEGORIES.items():
        for (name, effort, capital, hook) in cat_data["items"]:
            idea = {
                "id": make_id(name),
                "deck": "physical",
                "deckLabel": "Physical - online + offline",
                "channels": ["online", "offline"],
                "name": name,
                "hook": hook,
                "capital": capital,
                "effort": effort,
                "interests": cat_data["interests"],
                "image": f"https://images.unsplash.com/photo-{abs(hash(name)) % 10**10}?w=900&q=80",
                "bg": random.choice(["#C99A4B", "#4B7BC9", "#7B4BC9", "#4BC98A", "#C94B6E", "#4BAEC9", "#C9834B", "#6BC94B"]),
                "badges": make_badges(cat_data["badges_pool"]),
                "markets": ["US", "IN"],
                "capital_usd": {"low": int(capital.replace("$","").split("-")[0]), "high": int(capital.replace("$","").split("-")[1]) if "-" in capital else int(capital.replace("$","")) * 3},
                "breakdown": make_breakdown(name, "physical", capital, effort, cat_name),
            }
            physical_ideas.append(idea)

    # SaaS products
    for cat_name, cat_data in SAAS_CATEGORIES.items():
        for (name, effort, capital, hook) in cat_data["items"]:
            idea = {
                "id": make_id(name),
                "deck": "saas",
                "deckLabel": "SaaS - online",
                "channels": ["online"],
                "name": name,
                "hook": hook,
                "capital": capital,
                "effort": effort,
                "interests": cat_data["interests"],
                "image": f"https://images.unsplash.com/photo-{abs(hash(name)) % 10**10}?w=900&q=80",
                "bg": random.choice(["#4B7BC9", "#7B4BC9", "#4BC98A", "#4BAEC9", "#6BC94B"]),
                "badges": make_badges(cat_data["badges_pool"]),
                "markets": ["US", "IN"],
                "capital_usd": {"low": int(capital.replace("$","").split("-")[0]), "high": int(capital.replace("$","").split("-")[1]) if "-" in capital else int(capital.replace("$","")) * 3},
                "breakdown": make_breakdown(name, "saas", capital, effort, cat_name),
            }
            saas_ideas.append(idea)

    return physical_ideas, saas_ideas


def to_typescript(ideas, var_name):
    """Convert ideas list to TypeScript source."""
    lines = [f"// Auto-generated by generate-1000-ideas.py"]
    lines.append(f"// {len(ideas)} ideas")
    lines.append(f"import type {{ Idea }} from '../types'")
    lines.append(f"")
    lines.append(f"export const {var_name}: Idea[] = ")

    # Use JSON and fix the typing
    json_str = json.dumps(ideas, indent=2, ensure_ascii=False)
    lines.append(json_str)

    return "\n".join(lines)


if __name__ == "__main__":
    physical, saas = generate_all()

    print(f"Generated {len(physical)} physical ideas across {len(PHYSICAL_CATEGORIES)} categories")
    print(f"Generated {len(saas)} SaaS ideas across {len(SAAS_CATEGORIES)} categories")
    print(f"Total: {len(physical) + len(saas)} ideas")

    # Check for duplicate IDs
    all_ids = [i["id"] for i in physical + saas]
    dupes = [x for x in all_ids if all_ids.count(x) > 1]
    if dupes:
        print(f"\nWARNING: {len(set(dupes))} duplicate IDs found: {set(dupes)}")

    # Write TypeScript files
    import os
    out_dir = os.path.join(os.path.dirname(__file__), "..", "src", "data")

    with open(os.path.join(out_dir, "generated-physical.ts"), "w") as f:
        f.write(to_typescript(physical, "PHYSICAL_IDEAS"))
    print(f"\nWrote src/data/generated-physical.ts")

    with open(os.path.join(out_dir, "generated-saas.ts"), "w") as f:
        f.write(to_typescript(saas, "SAAS_IDEAS"))
    print(f"Wrote src/data/generated-saas.ts")

    # Print category breakdown
    print(f"\n=== Physical Categories ===")
    for cat, data in PHYSICAL_CATEGORIES.items():
        print(f"  {cat}: {len(data['items'])} ideas")

    print(f"\n=== SaaS Categories ===")
    for cat, data in SAAS_CATEGORIES.items():
        print(f"  {cat}: {len(data['items'])} ideas")
